#!/usr/bin/env bash
# todo: see cd-fzf

# map kitty_mod+f     launch --type=tab $HOME/.local/scripts/kitty-sessionizer
folders="$(pwd) $HOME/ $HOME/projects/ $HOME/projects/cp/ $HOME/projects/polimi/*/ \
$HOME/projects/.dotfiles/ $HOME/projects/.dotfiles/utils $HOME/projects/.dotfiles/nvim/lua/ \
$HOME/gitclone/ "

selected=$(find -L $(eval echo $folders) -mindepth 1 -maxdepth 1 -type d | fzf)
if ! [[ -z $selected ]]; then
    kitty @ launch --cwd=$selected --type=tab
fi
