#!/usr/bin/env bash
# map kitty_mod+f     launch --type=tab $HOME/.local/scripts/kitty-sessionizer
folders="$HOME/ $HOME/projects/ $HOME/projects/cp/ $HOME/projects/polimi/*/ \
$HOME/projects/.dotfiles/ $HOME/projects/.dotfiles/nvim/lua/ $(pwd)/"

selected=$(find -L $(eval echo $folders) -mindepth 1 -maxdepth 1 -type d | fzf)
if ! [[ -z $selected ]]; then
    kitty @ launch --cwd=$selected --type=tab
fi
