#!/usr/bin/env bash
SSPATH=$HOME/Pictures/Screenshots/screenshot-$(date +%y%m%d-%H%M%S).png
# # Hyprland
# grim -o $(hyprctl monitors -j | jq -r '.[] | select(.focused) | .name') $SSPATH
# Sway
grim -o $(swaymsg -t get_outputs  | jq -r '.[] | select(.focused) | .name') $SSPATH
wl-copy <$SSPATH
