#!/usr/bin/env bash
SSPATH=$HOME/Pictures/Screenshots/screenshot-$(date +%y%m%d-%H%M%S).png
# # Hyprland
# grim -g "$(hyprctl clients -j | jq -r ".[] | select(.workspace.id == "$(hyprctl activewindow -j | jq -r '.workspace.id')\)""| jq -r ".at,.size" | jq -s "add" | jq '_nwise(4)' | jq -r '"\(.[0]),\(.[1]) \(.[2])x\(.[3])"'| slurp)" "$SSPATH"
# Sway
grim -g "$(swaymsg -t get_tree | jq -r '.. | select(.focused?) | .rect | "\(.x),\(.y) \(.width)x\(.height)"')" "$SSPATH"
wl-copy <$SSPATH
