local mark = require("harpoon.mark")
local ui = require("harpoon.ui")

vim.keymap.set("n", "<bs>i", mark.add_file,{ desc = "Harpoon [I]nsert" })
vim.keymap.set("n", "<bs>u", ui.toggle_quick_menu, { desc = "Harpoon [U]i" })
vim.keymap.set("n", "<bs>h", function() ui.nav_file(1) end, { desc = "Harpoon 1" })
vim.keymap.set("n", "<bs>j", function() ui.nav_file(2) end, { desc = "Harpoon 2" })
vim.keymap.set("n", "<bs>k", function() ui.nav_file(4) end, { desc = "Harpoon 3" })
vim.keymap.set("n", "<bs>l", function() ui.nav_file(3) end, { desc = "Harpoon 4" })
vim.keymap.set("n", "<bs>;", function() ui.nav_file(3) end, { desc = "Harpoon 5" })
