#!/usr/bin/env bash

# sync with tmux-sessionizer
folders="$(pwd) /home $HOME/ $HOME/projects/ $HOME/projects/cp/ $HOME/projects/eth/*/ \
    $HOME/projects/dotfiles/ $HOME/projects/dotfiles/nvim/lua/ $HOME/gitclone/ "

selected=$(find -L $(eval echo $folders) -mindepth 1 -maxdepth 1 -type d | fzf)
if ! [[ -z $selected ]]; then
    cd $selected
fi
