#!/usr/bin/env bash
# todo: see kitty-sessionizer

folders="$(pwd) $HOME/ $HOME/projects/ $HOME/projects/cp/ $HOME/projects/polimi/*/ \
$HOME/projects/dotfiles/ $HOME/projects/dotfiles/nvim/lua/ $HOME/gitclone/ "

selected=$(find -L $(eval echo $folders) -mindepth 1 -maxdepth 1 -type d | fzf)
if ! [[ -z $selected ]]; then
    cd $selected
fi
