#!/usr/bin/env bash

# Usage:
# - no arguments -> set defaults
# - number       -> set cpu freq to that number in case it is in range [MIN_FREQ, MAX_FREQ]

# NOTE: be sure to adjust those to your systems ones
# cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq; cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
MIN_FREQ=400000
MAX_FREQ=4700000

NUM_CPUS=$(nproc)

# Reset to deafults
if [ -z "$1" ]; then
    for ((i = 0; i < NUM_CPUS; i++)); do
        sudo bash -c "echo $MIN_FREQ > /sys/devices/system/cpu/cpu$i/cpufreq/scaling_min_freq"
        sudo bash -c "echo $MAX_FREQ > /sys/devices/system/cpu/cpu$i/cpufreq/scaling_max_freq"
    done
    exit 0
fi

FIX_FREQ=$1

# Check if FIX_FREQ is a number
if ! [[ "$FIX_FREQ" =~ ^[0-9]+$ ]]; then
    echo "Error: FIX_FREQ must be a numeric value."
    exit 1
fi

# Validate FIX_FREQ is within range
if [ "$FIX_FREQ" -lt "$MIN_FREQ" ] || [ "$FIX_FREQ" -gt "$MAX_FREQ" ]; then
    echo "Error: FIX_FREQ must be between $MIN_FREQ and $MAX_FREQ."
    exit 1
fi

# Fix frequences
for ((i = 0; i < NUM_CPUS; i++)); do
    sudo bash -c "echo $FIX_FREQ > /sys/devices/system/cpu/cpu$i/cpufreq/scaling_min_freq"
    sudo bash -c "echo $FIX_FREQ > /sys/devices/system/cpu/cpu$i/cpufreq/scaling_max_freq"
done
