#!/usr/bin/env bash
STATUS=`hyprctl monitors -j | jq --arg monitor $1 -r '.[] | select(.name==$monitor) | .dpmsStatus'`

if [[ $STATUS == *"false"* ]]
then
    hyprctl dispatch dpms on $1
else
    hyprctl dispatch dpms off $1
fi
