#!/usr/bin/env bash

selection=$(bluetoothctl devices | awk '{for (i=3; i<=NF; i++) printf (i==NF ? $i : $i " "); print ""}' | fzf)
[ -z "$selection" ] && exit 0
bluetoothctl power on

if command -v pactl >/dev/null; then
    mac=$(bluetoothctl devices | grep -F "$selection" | awk '{print $2}')
    bluetoothctl connect $mac
    mac_dot=$(echo $mac | tr ':' '.')
    hp_sink=$(pactl list sinks short | awk '{print $2}' | sed -n "/$mac_dot/p" | sed -n '/output/p')
    if [[ -n "$hp_sink" ]]; then
        pactl set-default-sink $hp_sink
    fi
elif command -v wpctl >/dev/null; then
    sink_id=$(wpctl status | awk -v m="$selection" '
        /Sinks:/ {found=1}
        found && $0 ~ m {
            sub(/\./, "", $2);
            print $2;
            exit
        }
    ')
    [ -z "$sink_id" ] && exit 0
    if [[ "$sink_id" == "*" ]]; then
        echo "Channel already selected"
        exit 0
    fi
    wpctl set-default "$sink_id"
else
    echo "No method found"
fi
